development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost
production:
  adapter: postgresql
  encoding: unicode
  database: myapp_pro
  pool: 5
  username: postgres
  password: postgres
  host: localhost
